trigger:
- master
variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '857328a6-f501-4ae4-b917-d7da360e8cc5'
  
  # Web app name
  webAppName: 'node-express-demo-kannan-001'

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
  displayName: 'npm install, build and test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
